version: '3'
services:
  poststack:
    build: .
    environment:
      - JOB=poststack
      - CONFIG=data/config.yml
      - TOKEN=$TOKEN

    volumes:
      - ../data:/home/batchjobs/data

volumes:
  data:
