name: pylops
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python>=3.6.4
  - pip
  - numpy>=1.15.0
  - scipy
  - pyfftw
  - matplotlib
  - ipython
  - jupyter
  - numba
  - icc_rt
  - dask
  - pylops
  - pip:
    - spgl1